name: movies
description: Movie app with GraphQL.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  graphql_flutter: ^5.1.0
  quick_quotes_quill: ^2.0.0
  rxdart: ^0.27.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true